### ISSUE TITLE
Can this be run on other cores?

### ISSUE THREAD

**Issue by kocoman1** [jesusdf/grub-msr#1]
Can this be run on other cores?

**Comment by jesusdf** [comment]
Hi, on boot only one CPU core is initialized. GRUB does not wake up all the cores, since that is an OS task. This module is useful to change MSRs that have a global scope (for example the TDP of the CPU). I was also successful overclocking the CPU but only the core that was initialized.

Intel has a distribution based on GRUB that wakes up all cores and initializes a python interpreter to tests bioses, maybe that could be of any help:

https://github.com/biosbits/bits

**Comment by psyborg55** [comment]
Hi

I suppose your code is part of upstream grub sources, also trying to read a global scope MSR here but the rdmsr command fails, the shell freezes and does not respond anymore, only power cycle helps. The same MSR I can read in ubuntu, but I'll need to change it before OS loads. Any idea what is causing the hang or how to debug it?

**Comment by jesusdf** [comment]
You are right, the code is already upstream. If you try to read or write to a protected MSR, the CPU will raise a global protection fault and reset itself. To prevent this, It will be needed to implement a global exception handler in Grub, which is currently missing.
Test first in linux that the msr that you are trying to read and/or write to works before configuring it in grub.

**Comment by psyborg55** [comment]
yes the msr can be read/write to in linux
